/**
 * pkinative — x509-limbo path-validation scoring
 * =============================================
 * L1–L4 prove that pkinative **parses** what other implementations parse. This
 * module scores the other half: given a chain, a bag of intermediates, a trust
 * store, an instant and a host name, does pkinative reach the same verdict a
 * corpus of 9 793 hand-written cases says it should?
 *
 * ## Why a score and not a count
 *
 * `limbo-refusals.json` records which certificates are refused. That is a
 * regression detector: a red run says *"certificate ab3f… changed behaviour"*.
 * A score says *"this chain must be rejected and pkinative accepts it"*, which
 * is the only kind of statement a path validator's correctness can be made of.
 * Nothing before 0.5 could produce it, because nothing validated a path.
 *
 * ## The three things that make the number mean something
 *
 * **Reason codes, not the boolean.** A validator that rejects every chain
 * scores well on a corpus that is mostly FAILURE. So the reviewed subset in
 * `scripts/data/limbo-score.json → reasons` pins the `PkiReasonCode` too:
 * *rejected for the wrong reason* is a defect, and a boolean cannot see it.
 *
 * **Canaries.** One case that must succeed and one that must fail, named in the
 * baseline. A scorer whose harness silently broke — an exception swallowed, a
 * trust store not passed through — scores 100 % against a FAILURE-heavy corpus,
 * and the positive canary is what catches it. Same doctrine as L4's.
 *
 * **Every deviation carries a written reason.** A disagreement is either a
 * defect or a decision, and the difference is a sentence someone wrote. So the
 * baseline's `deviations` map is *not* regenerated by `--update-baseline`: the
 * tool records the id it measured, a human records why it is acceptable, and an
 * id with no `why` fails the gate. A baseline a tool can rewrite unattended is a
 * baseline that silently absorbs regressions.
 *
 * ## It scores the call callers make
 *
 * This runner composes nothing. It unwraps PEM, translates the corpus's
 * vocabulary into the library's — `validation_kind` into a key purpose,
 * `max_chain_depth` into a chain-length bound — and hands the whole question to
 * `verifyCertificateChain`. A harness that arranged the primitives itself would
 * score an arrangement that ships in no package, and the arrangement is exactly
 * the part a caller is most likely to get wrong.
 *
 * It cost the signature cache an earlier version kept: the layer verifies each
 * pair afresh, which is roughly a fifth more work here because the corpus reuses
 * its roots and almost never reuses a leaf. Paying it buys a number that is a
 * claim about the shipped entry point.
 *
 * **A lazier scheme was tried and measured being wrong**, and it is recorded
 * because the idea is a natural one. §6 takes verdicts precomputed, so something
 * must verify pairs before knowing which the path will use; the obvious saving
 * is a fixpoint — verify only the links of the path the builder reports, then
 * build again. When no verdict is known every path fails identically, so the
 * report is the *deepest* attempt, which is often a decoy, and once the decoy is
 * known invalid it is still the deepest. The good path's links are never asked
 * about. Fifteen cases the corpus expects to succeed were refused that way.
 *
 * @module scripts/lib/limbo-score
 */

import { createHash } from 'node:crypto';
import type * as Pki from '../../src/index.js';

/** One x509-limbo test case, as `limbo.json` writes it. */
export interface LimboScoreCase {
    readonly id: string;
    readonly expected_result: 'SUCCESS' | 'FAILURE';
    readonly features: readonly string[];
    readonly validation_kind: 'SERVER' | 'CLIENT';
    readonly validation_time: string | null;
    readonly trusted_certs: readonly string[];
    readonly untrusted_intermediates: readonly string[];
    readonly peer_certificate: string;
    readonly expected_peer_name: { readonly kind: string; readonly value: string } | null;
    readonly extended_key_usage: readonly string[];
    readonly max_chain_depth: number | null;
    readonly crls: readonly string[];
}

/** What scoring one case produced. */
export type CaseVerdict =
    | { readonly kind: 'scored'; readonly valid: boolean; readonly reasons: readonly string[] }
    | { readonly kind: 'skipped'; readonly why: string }
    /** A certificate the corpus holds and pkinative refuses: L1's business, not L6's. */
    | { readonly kind: 'unparsed'; readonly code: string };

/**
 * Features that make a case unanswerable rather than failed, with the reason.
 *
 * A SKIP is a claim too: *"this case asks for something pkinative does not do"*.
 * Each one names the reason here so a reader never has to guess whether a skip
 * is a decision or an oversight, and `--require-all` can be told to refuse new
 * ones.
 */
export const SKIP_FEATURES: Readonly<Record<string, string>> = Object.freeze({
    'has-mldsa': 'ML-DSA (FIPS 204) is not in Web Crypto, and pkinative implements no signature algorithm itself',
});

/**
 * x509-limbo names key purposes; RFC 5280 numbers them. Only the two the corpus
 * uses are here, because a name this table does not know would otherwise be
 * silently dropped, and a purpose silently not checked is a case that passes
 * for the wrong reason.
 */
const EKU_BY_NAME: Readonly<Record<string, string>> = Object.freeze({
    serverAuth: '1.3.6.1.5.5.7.3.1',
    clientAuth: '1.3.6.1.5.5.7.3.2',
});

const sha = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');

/**
 * Parsed certificates and signature verdicts, reused across every case.
 *
 * bettertls alone reuses one trust root across 9 572 cases, so caching by
 * SHA-256 of the DER turns the corpus from tens of thousands of key operations
 * into a few thousand.
 */
export interface ScoreCache {
    readonly certificates: Map<string, Pki.Certificate | { readonly refused: string }>;
    readonly signatures: Map<string, { verdict: Pki.SignatureVerdict; errorCode?: string; detail?: string }>;
    verifications: number;
}

/** A fresh cache. */
export function newScoreCache(): ScoreCache {
    return { certificates: new Map(), signatures: new Map(), verifications: 0 };
}

/** An IPv4 address as four octets, or null for anything else — including IPv6 text. */
function ipBytes(text: string): Uint8Array | null {
    if (text.includes(':')) return null;
    const parts = text.split('.').map(Number);
    return parts.length === 4 && parts.every((n) => Number.isInteger(n) && n >= 0 && n < 256)
        ? Uint8Array.from(parts)
        : null;
}

/**
 * Score one case: what pkinative says about it, in its own vocabulary.
 *
 * @param pki   The built package, imported from `dist/`.
 * @param test  One `limbo.json` case.
 * @param cache Parsed certificates and verdicts, shared across cases.
 * @returns The verdict, or why the case was not scored.
 */
export async function scoreCase(pki: typeof Pki, test: LimboScoreCase, cache: ScoreCache): Promise<CaseVerdict> {
    for (const feature of test.features) {
        const why = SKIP_FEATURES[feature];
        if (why !== undefined) return { kind: 'skipped', why };
    }

    const quiet = { onDiagnostic: (): undefined => undefined };
    const parse = (pem: string): Pki.Certificate[] | { refused: string } => {
        const out: Pki.Certificate[] = [];
        let blocks;
        try {
            blocks = pki.decodePem(pem, { label: 'CERTIFICATE', mode: 'lax', ...quiet });
        } catch (error) {
            return { refused: (error as { code?: string }).code ?? 'PKI_PEM_INVALID' };
        }
        for (const block of blocks) {
            const key = sha(block.bytes);
            let held = cache.certificates.get(key);
            if (held === undefined) {
                try {
                    held = pki.parseCertificate(block.bytes, quiet);
                } catch (error) {
                    held = { refused: (error as { code?: string }).code ?? 'PKI_X509_STRUCTURE_INVALID' };
                }
                cache.certificates.set(key, held);
            }
            if ('refused' in held) return held;
            out.push(held);
        }
        return out;
    };

    const leafBundle = parse(test.peer_certificate);
    if ('refused' in leafBundle) return { kind: 'unparsed', code: leafBundle.refused };
    const leaf = leafBundle[0];
    if (leaf === undefined) return { kind: 'skipped', why: 'the case carries no peer certificate' };

    const intermediates: Pki.Certificate[] = [];
    for (const pem of test.untrusted_intermediates) {
        const some = parse(pem);
        if ('refused' in some) return { kind: 'unparsed', code: some.refused };
        intermediates.push(...some);
    }
    const anchors: Pki.Certificate[] = [];
    for (const pem of test.trusted_certs) {
        const some = parse(pem);
        if ('refused' in some) return { kind: 'unparsed', code: some.refused };
        anchors.push(...some);
    }

    // `validation_time: null` means "now", which the corpus uses for cases whose
    // certificates have an open-ended window.
    const at = test.validation_time === null ? Date.now() : Date.parse(test.validation_time);

    // x509-limbo's `max_chain_depth` counts logical intermediates; a chain is
    // the leaf, those intermediates and the anchor.
    const limits = test.max_chain_depth === null
        ? { maxPathsExplored: 200 }
        : { maxPathsExplored: 200, maxChainLength: test.max_chain_depth + 2 };

    // Which purpose the chain has to serve. The corpus states it twice over: in
    // `extended_key_usage` for the 14 cases that name one, and in
    // `validation_kind` for every case, where SERVER means *validate this as a
    // TLS server certificate* and therefore serverAuth. Reading the second is
    // not an assumption of this harness — it is the field by which x509-limbo
    // records what a validation is for, and the bettertls suites it imports
    // wrote their FAILURE verdicts with purpose chaining enforced.
    const purposes = test.extended_key_usage.length > 0
        ? test.extended_key_usage.map((name) => EKU_BY_NAME[name] ?? name)
        : [test.validation_kind === 'CLIENT' ? '1.3.6.1.5.5.7.3.2' : '1.3.6.1.5.5.7.3.1'];

    // The host name, when the corpus names one. An IPv6 literal is skipped
    // rather than guessed: `ServerIdentity` takes octets, and turning text into
    // them is a parse this runner has no business doing on the library's behalf.
    const wanted = test.expected_peer_name;
    const identity: Pki.ServerIdentity | null = wanted === null
        ? null
        : wanted.kind === 'DNS'
            ? { kind: 'dns', value: wanted.value }
            : ((bytes) => bytes === null ? null : { kind: 'ip' as const, value: bytes })(ipBytes(wanted.value));

    // CRLs as DER, which is what the library takes: the runner unwraps the PEM
    // and stops there. A list it cannot even unwrap is dropped, because a
    // corpus case carrying an unreadable envelope is not asking a question
    // about revocation.
    const crls: Uint8Array[] = [];
    for (const pem of test.crls) {
        try {
            for (const block of pki.decodePem(pem, { label: 'X509 CRL', mode: 'lax', ...quiet })) crls.push(block.bytes);
        } catch {
            continue;
        }
    }

    // **One call, the one callers make.** Composing the primitives here instead
    // would score an arrangement that ships in no package: the number below is
    // meant to be a claim about `verifyCertificateChain`, so it is the thing
    // being measured. It costs the signature cache this runner used to keep —
    // roughly a fifth of the work, since the corpus reuses roots but almost
    // never reuses a leaf — and buys a score about the shipped entry point.
    const report = await pki.verifyCertificateChain({
        leaf,
        candidates: intermediates,
        trustAnchors: anchors,
        at,
        limits,
        purposes,
        ...(identity === null ? {} : { serverName: identity }),
        ...(crls.length === 0 ? {} : { crls }),
    });
    cache.verifications += report.signatureVerifications;
    const reasons = report.reasons.map((reason) => reason.code);

    return { kind: 'scored', valid: report.valid && reasons.length === 0, reasons };
}
