/**
 * pkinative — x509-limbo path-validation scoring
 * =============================================
 * L1–L4 prove that pkinative **parses** what other implementations parse. This
 * module scores the other half: given a chain, a bag of intermediates, a trust
 * store, an instant and a host name, does pkinative reach the same verdict a
 * corpus of 9 793 hand-written cases says it should?
 *
 * ## Why a score and not a count
 *
 * `limbo-refusals.json` records which certificates are refused. That is a
 * regression detector: a red run says *"certificate ab3f… changed behaviour"*.
 * A score says *"this chain must be rejected and pkinative accepts it"*, which
 * is the only kind of statement a path validator's correctness can be made of.
 * Nothing before 0.5 could produce it, because nothing validated a path.
 *
 * ## The three things that make the number mean something
 *
 * **Reason codes, not the boolean.** A validator that rejects every chain
 * scores well on a corpus that is mostly FAILURE. So the reviewed subset in
 * `scripts/data/limbo-score.json → reasons` pins the `PkiReasonCode` too:
 * *rejected for the wrong reason* is a defect, and a boolean cannot see it.
 *
 * **Canaries.** One case that must succeed and one that must fail, named in the
 * baseline. A scorer whose harness silently broke — an exception swallowed, a
 * trust store not passed through — scores 100 % against a FAILURE-heavy corpus,
 * and the positive canary is what catches it. Same doctrine as L4's.
 *
 * **Every deviation carries a written reason.** A disagreement is either a
 * defect or a decision, and the difference is a sentence someone wrote. So the
 * baseline's `deviations` map is *not* regenerated by `--update-baseline`: the
 * tool records the id it measured, a human records why it is acceptable, and an
 * id with no `why` fails the gate. A baseline a tool can rewrite unattended is a
 * baseline that silently absorbs regressions.
 *
 * ## Every reachable pair is verified, and a lazier scheme was tried and rejected
 *
 * `validateCertificatePath` takes verdicts precomputed — that is what keeps §6
 * synchronous — so a scorer must verify pairs before it knows which ones the
 * path will use. That costs tens of thousands of public-key operations over the
 * corpus, and the obvious saving is a fixpoint: build with what is known, verify
 * the links of the path the builder reports, build again.
 *
 * **It is wrong, and it was measured being wrong.** When no verdict is known
 * every path fails identically, so the report is the *deepest* attempt, which is
 * often a decoy — and once the decoy's links are verified and found invalid it
 * is still the deepest attempt. The good path's links are never asked about, and
 * the loop stalls on a chain it should have accepted: 15 cases the corpus expects
 * to succeed were refused that way.
 *
 * So every pair the builder could use is verified up front. "Could use" is not
 * "exists": the builder only walks name chains **from the leaf**, so the bag is
 * first reduced to the certificates reachable that way, which prunes a large
 * trust store without changing a single verdict.
 *
 * @module scripts/lib/limbo-score
 */

import { createHash } from 'node:crypto';
import type * as Pki from '../../src/index.js';

/** One x509-limbo test case, as `limbo.json` writes it. */
export interface LimboScoreCase {
    readonly id: string;
    readonly expected_result: 'SUCCESS' | 'FAILURE';
    readonly features: readonly string[];
    readonly validation_kind: 'SERVER' | 'CLIENT';
    readonly validation_time: string | null;
    readonly trusted_certs: readonly string[];
    readonly untrusted_intermediates: readonly string[];
    readonly peer_certificate: string;
    readonly expected_peer_name: { readonly kind: string; readonly value: string } | null;
    readonly extended_key_usage: readonly string[];
    readonly max_chain_depth: number | null;
    readonly crls: readonly string[];
}

/** What scoring one case produced. */
export type CaseVerdict =
    | { readonly kind: 'scored'; readonly valid: boolean; readonly reasons: readonly string[] }
    | { readonly kind: 'skipped'; readonly why: string }
    /** A certificate the corpus holds and pkinative refuses: L1's business, not L6's. */
    | { readonly kind: 'unparsed'; readonly code: string };

/**
 * Features that make a case unanswerable rather than failed, with the reason.
 *
 * A SKIP is a claim too: *"this case asks for something pkinative does not do"*.
 * Each one names the reason here so a reader never has to guess whether a skip
 * is a decision or an oversight, and `--require-all` can be told to refuse new
 * ones.
 */
export const SKIP_FEATURES: Readonly<Record<string, string>> = Object.freeze({
    'has-mldsa': 'ML-DSA (FIPS 204) is not in Web Crypto, and pkinative implements no signature algorithm itself',
});

/**
 * x509-limbo names key purposes; RFC 5280 numbers them. Only the two the corpus
 * uses are here, because a name this table does not know would otherwise be
 * silently dropped, and a purpose silently not checked is a case that passes
 * for the wrong reason.
 */
const EKU_BY_NAME: Readonly<Record<string, string>> = Object.freeze({
    serverAuth: '1.3.6.1.5.5.7.3.1',
    clientAuth: '1.3.6.1.5.5.7.3.2',
});

const sha = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex');
const hex = (bytes: Uint8Array): string => Buffer.from(bytes).toString('hex');

/**
 * Parsed certificates and signature verdicts, reused across every case.
 *
 * bettertls alone reuses one trust root across 9 572 cases, so caching by
 * SHA-256 of the DER turns the corpus from tens of thousands of key operations
 * into a few thousand.
 */
export interface ScoreCache {
    readonly certificates: Map<string, Pki.Certificate | { readonly refused: string }>;
    readonly signatures: Map<string, { verdict: Pki.SignatureVerdict; errorCode?: string; detail?: string }>;
    verifications: number;
}

/** A fresh cache. */
export function newScoreCache(): ScoreCache {
    return { certificates: new Map(), signatures: new Map(), verifications: 0 };
}

/** An IPv4 address as four octets, or null for anything else — including IPv6 text. */
function ipBytes(text: string): Uint8Array | null {
    if (text.includes(':')) return null;
    const parts = text.split('.').map(Number);
    return parts.length === 4 && parts.every((n) => Number.isInteger(n) && n >= 0 && n < 256)
        ? Uint8Array.from(parts)
        : null;
}

/**
 * Score one case: what pkinative says about it, in its own vocabulary.
 *
 * @param pki   The built package, imported from `dist/`.
 * @param test  One `limbo.json` case.
 * @param cache Parsed certificates and verdicts, shared across cases.
 * @returns The verdict, or why the case was not scored.
 */
export async function scoreCase(pki: typeof Pki, test: LimboScoreCase, cache: ScoreCache): Promise<CaseVerdict> {
    for (const feature of test.features) {
        const why = SKIP_FEATURES[feature];
        if (why !== undefined) return { kind: 'skipped', why };
    }

    const quiet = { onDiagnostic: (): undefined => undefined };
    const parse = (pem: string): Pki.Certificate[] | { refused: string } => {
        const out: Pki.Certificate[] = [];
        let blocks;
        try {
            blocks = pki.decodePem(pem, { label: 'CERTIFICATE', mode: 'lax', ...quiet });
        } catch (error) {
            return { refused: (error as { code?: string }).code ?? 'PKI_PEM_INVALID' };
        }
        for (const block of blocks) {
            const key = sha(block.bytes);
            let held = cache.certificates.get(key);
            if (held === undefined) {
                try {
                    held = pki.parseCertificate(block.bytes, quiet);
                } catch (error) {
                    held = { refused: (error as { code?: string }).code ?? 'PKI_X509_STRUCTURE_INVALID' };
                }
                cache.certificates.set(key, held);
            }
            if ('refused' in held) return held;
            out.push(held);
        }
        return out;
    };

    const leafBundle = parse(test.peer_certificate);
    if ('refused' in leafBundle) return { kind: 'unparsed', code: leafBundle.refused };
    const leaf = leafBundle[0];
    if (leaf === undefined) return { kind: 'skipped', why: 'the case carries no peer certificate' };

    const intermediates: Pki.Certificate[] = [];
    for (const pem of test.untrusted_intermediates) {
        const some = parse(pem);
        if ('refused' in some) return { kind: 'unparsed', code: some.refused };
        intermediates.push(...some);
    }
    const anchors: Pki.Certificate[] = [];
    for (const pem of test.trusted_certs) {
        const some = parse(pem);
        if ('refused' in some) return { kind: 'unparsed', code: some.refused };
        anchors.push(...some);
    }

    // `validation_time: null` means "now", which the corpus uses for cases whose
    // certificates have an open-ended window.
    const at = test.validation_time === null ? Date.now() : Date.parse(test.validation_time);
    const all = [leaf, ...intermediates, ...anchors];

    const verdictFor = async (subject: Pki.Certificate, issuer: Pki.Certificate): Promise<Pki.SignatureResult> => {
        const key = `${sha(subject.der)}|${sha(issuer.der)}`;
        let held = cache.signatures.get(key);
        if (held === undefined) {
            cache.verifications += 1;
            try {
                held = { verdict: await pki.verifyCertificateSignature(subject, issuer) ? 'valid' : 'invalid' };
            } catch (error) {
                const { code, message } = error as { code?: string; message?: string };
                held = { verdict: 'not-checked', errorCode: code ?? 'PKI_CRYPTO_UNAVAILABLE', detail: message ?? '' };
            }
            cache.signatures.set(key, held);
        }
        // The issuer is named on every result: two candidates sharing a subject
        // name is what this corpus is full of, and a verdict that does not say
        // which issuer it is about cannot decide between them.
        return { certificate: subject, issuer, ...held };
    };

    // x509-limbo's `max_chain_depth` counts logical intermediates; a chain is
    // the leaf, those intermediates and the anchor.
    const limits = test.max_chain_depth === null
        ? { maxPathsExplored: 200 }
        : { maxPathsExplored: 200, maxChainLength: test.max_chain_depth + 2 };
    const wantedPurposes = test.extended_key_usage.length > 0
        ? test.extended_key_usage.map((name) => EKU_BY_NAME[name] ?? name)
        : [test.validation_kind === 'CLIENT' ? '1.3.6.1.5.5.7.3.2' : '1.3.6.1.5.5.7.3.1'];

    // Index the bag by encoded subject name, then keep only what a name chain
    // from the leaf can reach. The builder walks nothing else, so a pair outside
    // this closure could not change an answer — and a trust store of hundreds is
    // reduced to the handful that name the right subjects.
    const bySubject = new Map<string, Pki.Certificate[]>();
    for (const candidate of all) {
        const key = hex(candidate.subject.der);
        bySubject.set(key, [...(bySubject.get(key) ?? []), candidate]);
    }
    const signatures: Pki.SignatureResult[] = [];
    const walked = new Set<Pki.Certificate>();
    const queue: Pki.Certificate[] = [leaf];
    while (queue.length > 0) {
        const subject = queue.pop() as Pki.Certificate;
        if (walked.has(subject)) continue;
        walked.add(subject);
        for (const issuer of bySubject.get(hex(subject.issuer.der)) ?? []) {
            // A self-signed certificate is not a link to verify: §6 does not
            // check a trust anchor's own signature, and following the edge would
            // loop.
            if (issuer === subject) continue;
            signatures.push(await verdictFor(subject, issuer));
            queue.push(issuer);
        }
    }

    const report = pki.buildCertificatePath({
        leaf, candidates: intermediates, trustAnchors: anchors, at, signatures, limits,
        requiredPurposes: wantedPurposes,
    });
    const reasons = report.reasons.map((reason) => reason.code);

    // Revocation is a separate question from §6, asked the way a caller would.
    for (const pem of test.crls) {
        let blocks;
        try {
            blocks = pki.decodePem(pem, { label: 'X509 CRL', mode: 'lax', ...quiet });
        } catch {
            continue;
        }
        for (const block of blocks) {
            let crl;
            try {
                crl = pki.parseCertificateList(block.bytes, quiet);
            } catch (error) {
                return { kind: 'unparsed', code: (error as { code?: string }).code ?? 'PKI_X509_STRUCTURE_INVALID' };
            }
            // The list is only evidence if a key entitled to sign it did.
            let signatureVerified: boolean | undefined;
            for (const candidate of all) {
                if (hex(crl.issuer.der) !== hex(candidate.subject.der)) continue;
                try {
                    signatureVerified = await pki.verifyCrlSignature(crl, candidate);
                } catch {
                    signatureVerified = undefined;
                }
                if (signatureVerified === true) break;
            }
            const input: Pki.RevocationCheckInput = { certificate: leaf, crl, crlDer: block.bytes, at, options: quiet };
            reasons.push(...pki.checkRevocation(signatureVerified === undefined ? input : { ...input, signatureVerified })
                .map((reason) => reason.code));
        }
    }

    // Name matching is a separate question too, and both are needed: a chain
    // from nobody in particular and a certificate for somebody else are two
    // different failures, and §6 sees only the first.
    const wanted = test.expected_peer_name;
    if (wanted !== null) {
        const identity: Pki.ServerIdentity | null = wanted.kind === 'DNS'
            ? { kind: 'dns', value: wanted.value }
            : ((bytes) => bytes === null ? null : { kind: 'ip' as const, value: bytes })(ipBytes(wanted.value));
        if (identity !== null) reasons.push(...pki.checkServerName(leaf, identity).map((reason) => reason.code));
    }

    // And so is the purpose. RFC 5280 §6 never reads extKeyUsage: which purpose
    // a chain has to serve is a fact about the caller's protocol, and the corpus
    // states it twice over — in `extended_key_usage` for the 14 cases that name
    // one, and in `validation_kind` for every case, where SERVER means *validate
    // this as a TLS server certificate* and therefore serverAuth.
    //
    // Reading `validation_kind` as a purpose is not an assumption of this
    // harness: it is the field by which x509-limbo records what the validation
    // is for, and the bettertls suites it imports wrote their FAILURE verdicts
    // with purpose chaining enforced. Turning it on found a real defect in path
    // *building* rather than in the purpose check — see `requiredPurposes` in
    // `buildCertificatePath`.
    const named = test.extended_key_usage.map((name) => EKU_BY_NAME[name] ?? name);
    // A purpose whose name this harness cannot map would be dropped, and a
    // purpose silently not checked is a case that passes for the wrong reason —
    // so it is a skip with the name in it rather than a quiet omission.
    const unknown = test.extended_key_usage.filter((name) => EKU_BY_NAME[name] === undefined);
    if (unknown.length > 0) {
        return { kind: 'skipped', why: `the case names the key purpose(s) ${unknown.join(', ')}, which this runner does not map to an OID` };
    }
    const purposes = named.length > 0
        ? named
        : [test.validation_kind === 'CLIENT' ? pki.KEY_PURPOSES.clientAuth : pki.KEY_PURPOSES.serverAuth];
    // The purposes go **into** the search, not after it: a builder that picks a
    // path without knowing what the path is for will confidently return one a
    // later check condemns while an acceptable one existed. The check below is
    // then a restatement on the path that was chosen, and it runs only when §6
    // accepted that path — `report.path` is the best attempt otherwise, and
    // judging a partial chain would put reasons about certificates that are on
    // no accepted path into the pinned reason codes.
    if (report.valid) {
        for (const purpose of purposes) {
            reasons.push(...pki.checkExtendedKeyUsage(report.path, purpose).map((reason) => reason.code));
        }
    }

    return { kind: 'scored', valid: report.valid && reasons.length === 0, reasons };
}
