/**
 * pkinative — the decision surface, as data
 * ==========================================
 * The third leg of the 1.0 compatibility promise (ADR 0014): which corpus
 * certificate pkinative refuses, and with which code. Two files carry it.
 *
 *   - `scripts/data/limbo-refusals.json`, the **baseline**: what the engine
 *     refuses today, SHA-256 of the DER → `PkiErrorCode`, rewritten by
 *     `validate-certs.ts --update-baseline` and verified against the corpus
 *     by conformance L1 on every run.
 *   - `docs/data/refusals.frozen.json`, the **snapshot**: what is promised.
 *     Written only by scripts/build-refusals-frozen.ts, in the ways ADR 0014
 *     allows; held to the baseline offline by the `refusal-baseline-frozen`
 *     rule of verify-docs, and read directly by conformance L1.
 *
 * This module is the shared, pure half: parsing, rendering and the diff.
 *
 * @module scripts/lib/refusals-frozen
 */

export const REFUSALS_FROZEN = 'docs/data/refusals.frozen.json';
export const REFUSAL_BASELINE = 'scripts/data/limbo-refusals.json';
export const REFUSALS_GENERATOR = 'npx tsx scripts/build-refusals-frozen.ts';
/** The heading of a release note under which the refusals it adds are listed. */
export const DECISION_SURFACE_HEADING = '### Decision surface';
/** How many hex digits of a SHA-256 a release note must quote for each refusal it adds. */
export const HASH_PREFIX = 16;

export type RefusalPhase = 'rehearsal' | 'stable';

/** One promised refusal. `since` is present only on a refusal a stable-phase release added. */
export interface FrozenRefusal {
    readonly sha256: string;
    readonly code: string;
    readonly since?: string | undefined;
}

/** A promised refusal whose certificate a corpus re-pin dropped: still promised, verified only where a corpus holds it. */
export interface RetiredRefusal {
    readonly sha256: string;
    readonly code: string;
    /** The corpus commit it was last verified at. */
    readonly commit: string;
    /** The accepted ADR that records the re-pin. */
    readonly adr: string;
}

export interface RefusalsFrozen {
    readonly frozenAt: string;
    readonly phase: RefusalPhase;
    readonly asOf: string;
    readonly corpus: string;
    readonly commit: string;
    readonly refusals: readonly FrozenRefusal[];
    readonly retired?: readonly RetiredRefusal[] | undefined;
}

export interface RefusalBaseline {
    readonly corpus: string;
    readonly commit: string;
    readonly refusals: ReadonlyMap<string, string>;
}

const SEMVER = /^\d+\.\d+\.\d+$/;
const SHA256 = /^[0-9a-f]{64}$/;
const COMMIT = /^[0-9a-f]{40}$/;

const COMMENT =
    'The decision surface of pkinative under semantic versioning (ADR 0014), generated by scripts/build-refusals-frozen.ts from scripts/data/limbo-refusals.json: every x509-limbo certificate '
    + 'parseCertificate refuses under the default options, by the SHA-256 of its DER, with the PkiErrorCode it is refused with, as verified by conformance L1 at "commit". '
    + 'The refusal-baseline-frozen rule of scripts/verify-docs.ts fails when a refusal listed here leaves the baseline or changes code, and conformance L1 fails when the corpus holds a listed certificate and the engine does not refuse it with that code: both are semver-major. '
    + 'phase "rehearsal" (0.9.x): no refusal may be added either. phase "stable" (from 1.0.0): a new refusal is a recorded security or conformance fix, semver-minor — the release that ships it adds it here with its "since", and its release note lists it under "### Decision surface". '
    + '"retired" holds refusals whose certificate a corpus re-pin dropped, with the commit they were last verified at and the ADR that records the re-pin: still promised. Path verdicts, diagnostics, limit defaults and scores are not part of this file.';

/** The baseline, or null when the text is not one. */
export function parseRefusalBaseline(text: string | null): RefusalBaseline | null {
    if (text === null) return null;
    try {
        const v = JSON.parse(text) as { corpus?: unknown; commit?: unknown; refusals?: unknown };
        if (typeof v.corpus !== 'string' || typeof v.commit !== 'string' || typeof v.refusals !== 'object' || v.refusals === null || Array.isArray(v.refusals)) return null;
        const refusals = new Map<string, string>();
        for (const [hash, code] of Object.entries(v.refusals as Record<string, unknown>)) {
            if (typeof code !== 'string') return null;
            refusals.set(hash, code);
        }
        return { corpus: v.corpus, commit: v.commit, refusals };
    } catch {
        return null;
    }
}

/**
 * The snapshot, or a list of what is wrong with its shape. Every check that
 * does not need another file lives here, so that the rule and the generator
 * refuse the same malformed file for the same reason.
 */
export function parseRefusalsFrozen(text: string): { readonly snapshot: RefusalsFrozen } | { readonly problems: readonly string[] } {
    let v: Partial<Record<keyof RefusalsFrozen, unknown>>;
    try {
        v = JSON.parse(text) as typeof v;
    } catch (err) {
        return { problems: [`not JSON: ${(err as Error).message}`] };
    }
    const problems: string[] = [];
    if (typeof v.frozenAt !== 'string' || !SEMVER.test(v.frozenAt) || typeof v.asOf !== 'string' || !SEMVER.test(v.asOf)) problems.push('"frozenAt" and "asOf" must be x.y.z versions');
    if (v.phase !== 'rehearsal' && v.phase !== 'stable') problems.push('"phase" must be "rehearsal" or "stable"');
    if (typeof v.corpus !== 'string' || v.corpus === '') problems.push('"corpus" must name the corpus the refusals were verified against');
    if (typeof v.commit !== 'string' || !COMMIT.test(v.commit)) problems.push('"commit" must be the 40-hex corpus commit the refusals were last verified at');
    if (!Array.isArray(v.refusals)) problems.push('"refusals" must be a list of { sha256, code }');
    if (v.retired !== undefined && !Array.isArray(v.retired)) problems.push('"retired" must be a list of { sha256, code, commit, adr }');
    if (problems.length > 0) return { problems };

    const seen = new Set<string>();
    for (const row of v.refusals as Array<Partial<FrozenRefusal>>) {
        const hash = typeof row?.sha256 === 'string' ? row.sha256 : '';
        if (!SHA256.test(hash) || typeof row.code !== 'string' || row.code === '') { problems.push(`a refusal row needs a 64-hex "sha256" and a "code" (${JSON.stringify(row)})`); continue; }
        if (seen.has(hash)) problems.push(`${hash} is listed twice`);
        seen.add(hash);
        if (row.since !== undefined) {
            if (typeof row.since !== 'string' || !SEMVER.test(row.since)) problems.push(`${hash}: "since" must be an x.y.z version`);
            else if (v.phase !== 'stable') problems.push(`${hash}: carries "since" ${row.since} in the rehearsal — only a stable-phase release adds a refusal`);
        }
    }
    for (const row of (v.retired ?? []) as Array<Partial<RetiredRefusal>>) {
        const hash = typeof row?.sha256 === 'string' ? row.sha256 : '';
        if (!SHA256.test(hash) || typeof row.code !== 'string' || typeof row.commit !== 'string' || !COMMIT.test(row.commit) || typeof row.adr !== 'string') {
            problems.push(`a retired row needs "sha256", "code", "commit" and "adr" (${JSON.stringify(row)})`);
            continue;
        }
        if (seen.has(hash)) problems.push(`${hash} is listed twice`);
        seen.add(hash);
        if (row.commit === v.commit) problems.push(`${hash} is retired at ${row.commit}, the commit the snapshot is verified at — a refusal is retired only by a re-pin that dropped its certificate`);
    }
    return problems.length > 0 ? { problems } : { snapshot: v as unknown as RefusalsFrozen };
}

/** The snapshot text, one refusal per line so that a diff reads as the decisions that moved. */
export function renderRefusalsFrozen(s: RefusalsFrozen): string {
    const row = (r: FrozenRefusal): string => `    { "sha256": ${JSON.stringify(r.sha256)}, "code": ${JSON.stringify(r.code)}${r.since === undefined ? '' : `, "since": ${JSON.stringify(r.since)}`} }`;
    const retired = s.retired ?? [];
    const retiredBlock = retired.length === 0 ? '' : `,\n  "retired": [\n${retired.map((r) => `    { "sha256": ${JSON.stringify(r.sha256)}, "code": ${JSON.stringify(r.code)}, "commit": ${JSON.stringify(r.commit)}, "adr": ${JSON.stringify(r.adr)} }`).join(',\n')}\n  ]`;
    return `{\n  "$comment": ${JSON.stringify(COMMENT)},\n  "frozenAt": ${JSON.stringify(s.frozenAt)},\n  "phase": ${JSON.stringify(s.phase)},\n  "asOf": ${JSON.stringify(s.asOf)},\n`
        + `  "corpus": ${JSON.stringify(s.corpus)},\n  "commit": ${JSON.stringify(s.commit)},\n  "refusals": [\n${[...s.refusals].sort(byHash).map(row).join(',\n')}\n  ]${retiredBlock}\n}\n`;
}

const byHash = (a: { readonly sha256: string }, b: { readonly sha256: string }): number => (a.sha256 < b.sha256 ? -1 : a.sha256 > b.sha256 ? 1 : 0);

export interface RefusalDrift {
    /** Promised refusals the baseline no longer lists: the certificate parses, or left the corpus. */
    readonly lifted: readonly FrozenRefusal[];
    /** Promised refusals the baseline lists with another code. */
    readonly recoded: ReadonlyArray<{ readonly row: FrozenRefusal | RetiredRefusal; readonly now: string }>;
    /** Baseline refusals the snapshot does not promise yet, in hash order. */
    readonly added: ReadonlyArray<{ readonly sha256: string; readonly code: string }>;
}

/** How the baseline differs from the snapshot. A retired refusal is never "lifted" (its certificate is gone), but it may not come back under another code. */
export function diffRefusals(snapshot: RefusalsFrozen, baseline: RefusalBaseline): RefusalDrift {
    const lifted: FrozenRefusal[] = [];
    const recoded: Array<{ row: FrozenRefusal | RetiredRefusal; now: string }> = [];
    const promised = new Set<string>();
    for (const row of snapshot.refusals) {
        promised.add(row.sha256);
        const now = baseline.refusals.get(row.sha256);
        if (now === undefined) lifted.push(row);
        else if (now !== row.code) recoded.push({ row, now });
    }
    for (const row of snapshot.retired ?? []) {
        promised.add(row.sha256);
        const now = baseline.refusals.get(row.sha256);
        if (now !== undefined && now !== row.code) recoded.push({ row, now });
    }
    const added = [...baseline.refusals].filter(([hash]) => !promised.has(hash)).map(([sha256, code]) => ({ sha256, code })).sort(byHash);
    return { lifted, recoded, added };
}

/** The section of a release note under DECISION_SURFACE_HEADING, or null when the note has none. */
export function decisionSurfaceSection(note: string): string | null {
    const lines = note.replace(/\r\n/g, '\n').split('\n');
    const start = lines.findIndex((l) => l.trim() === DECISION_SURFACE_HEADING);
    if (start < 0) return null;
    const end = lines.findIndex((l, i) => i > start && /^#{1,3} /.test(l));
    return lines.slice(start + 1, end < 0 ? undefined : end).join('\n');
}
