// pkinative — runtime smoke checks
// ================================
// One parse, one verify per signature family and one PKCS#12 round trip,
// run against the BUILT package (dist/index.js) on a runtime other than
// Node: Deno, Bun and headless Chromium (.github/workflows/ci.yml, job
// `runtimes`). README.md and the landing page say the same build runs
// there; this is what holds that sentence to a run instead of a belief.
//
// Plain ESM with no import of its own and no host API beyond what every
// target exposes — `globalThis.crypto.subtle`, `atob`, `TextEncoder` — so the
// one file runs unchanged in all of them. The fixtures are inlined:
//   X1  tests/fixtures/certs/isrg-root-x1.der (RSA 4096, sha256WithRSAEncryption)
//   X2  tests/fixtures/certs/isrg-root-x2.der (P-384, ecdsa-with-SHA384)
//   P12 a P-256 key and its self-signed certificate written by OpenSSL 3.5.5:
//       `openssl pkcs12 -export -pbmac1_pbkdf2 -passout pass:smoke` — PBES2,
//       PBKDF2-HMAC-SHA256, AES-256-CBC, integrity by PBMAC1 (RFC 9579).
//   ED448_ROOT, ED448_P7S  an Ed25519 root and a CMS SignedData whose one
//       signer holds an Ed448 key under a certificate that root issued,
//       digesting with SHAKE256 (RFC 8419 §3.1); the content is attached.
//       Written once by node:crypto and pkinative's own builders, because
//       a runtime without Ed448 cannot make the key, and the check's point
//       is what each runtime answers for it (ADR 0022).
// The Ed25519 key of the Ed25519 check is generated by the runtime itself:
// the smoke harness may call generateKey, the library never does.

const X1 ='MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAwTzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2VhcmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygch77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6UA5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sWT8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyHB5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UCB5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUvKBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWnOlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTnjh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbwqHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CIrU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkqhkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZLubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KKNFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7UrTkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdCjNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVcoyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPAmRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57demyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=';
const X2 = 'MIICGzCCAaGgAwIBAgIQQdKd0XLq7qeAwSxs6S+HUjAKBggqhkjOPQQDAzBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMjAeFw0yMDA5MDQwMDAwMDBaFw00MDA5MTcxNjAwMDBaME8xCzAJBgNVBAYTAlVTMSkwJwYDVQQKEyBJbnRlcm5ldCBTZWN1cml0eSBSZXNlYXJjaCBHcm91cDEVMBMGA1UEAxMMSVNSRyBSb290IFgyMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEzZvVn4CDCuwJSvMWSj5cz3es3mcFDR0HttwW+1qLFNvicWDEukWVEYmO6gbf9yoWHKS5xcUy4APgHoIYOIvXRdgKam7mAHf7AlF9ItgKbppbd9/w+kHsOdx1ymgHDB/qo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUfEKWrt5LSDv6kviejM9ti6lyN5UwCgYIKoZIzj0EAwMDaAAwZQIwe3lORlCEwkSHRhtFcP9Ymd70/aTSVaYgLXTWNLxBo1BfASdWtL4ndQavEi51mI38AjEAi/V3bNTIZargCyzuFJ0nN6T5U6VR5CmD1/iQMVtCnwr1/q4AaOeMSQ+2b1tbFfLn';
const P12 = 'MIIEswIBAzCCBC0GCSqGSIb3DQEHAaCCBB4EggQaMIIEFjCCAqoGCSqGSIb3DQEHBqCCApswggKXAgEAMIICkAYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqGSIb3DQEFDDAkBBAyfLIliFYTcvl95YmlinO/AgIIADAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQVb1V5FjD2Yu+/+FLaqmBtYCCAiAU4IomYMZFJJuo5AOPqbWDvGxG76TdviWFa6Ngu6alFaDyv4KND+UM8Z3V7vgBm3vgo2hl5DPKbYS8h+PbzAOw96xMxjG1E+8pR1JTJfwd0YUBTpidikhLgEey352KaN84By8SRHKaem6XtO+X9HPEQEkkj37oJ2uOHKJMIez1pp6PFXRccyAEsZfGs1EZhRLwZ10hYmldx9ZKyuTv03Hx2WTNcexTYxor2wlTxzM8s4Gr9XpRgy6G+Yc5jq8JwMWHKPbq24143TothplzhYT0uD+HHktcAMEK0VIn4OY8Kbv+kEV5qqQZvlj3EK1jC55RnwJKgMFogdZgAjnVWmsWOAmeFMuY9GmSYFu8hb5JmudA8Y5bjQSc3Puamu6ifen6PDp6KO9MvjonRKOhBv7Lrica5+drEDd4b9/B1S2FTGbjUQxCXuVLdiVKL9F+HmraPLYL7MhTFksQ8vwXW+gKQrhZ+MfneTDh4c9AkmbN/wZX/lf2kFQLGrVQrSUD30I4ZjdT0kbf7fl8ZRNijFU6ni5bpg20ASeRIo9JqMS0zNuMcGfTa2jlybhZ/V4XYgZB2AXMXiK1NnljPjSWPpFTa/anWJX15Bc7S3JHf1UWPyHx9bLi1qst5Dm8aRYNXhsvYAs8J0yx3Z+zy2qZX6PwpawvuW8ywk8ZDsjTDGUGVkLCpDCzP8eFjnfUjgOxYHE4IGHA85RKJc7fta5NnXYJMIIBZAYJKoZIhvcNAQcBoIIBVQSCAVEwggFNMIIBSQYLKoZIhvcNAQwKAQKggfcwgfQwXwYJKoZIhvcNAQUNMFIwMQYJKoZIhvcNAQUMMCQEEIoHPmZe0KMGcq4FFaxQEVACAggAMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBCU6i49GFTf70ONGFb7r+RnBIGQknSmoTkGGX+zupKsqjDkz1NB4VFbcBwunmIFKC16MzFe/wt83jAvsny0IwQUM8s5LfZKV0p/i+iIvP+YWF8KccJppfDOvtd52B3en6a20GkhstxBJKCKKN1Ew68rER1yMQQhLCIUCWmzhycOblU3NG3/spN8KoWwg/kR81CpIXScLKl2FLmcK7+2K+OdlylUMUAwGQYJKoZIhvcNAQkUMQweCgBzAG0AbwBrAGUwIwYJKoZIhvcNAQkVMRYEFGuhBNws0Uv+VD5OkgjccIDq+8mlMH0wbTBJBgkqhkiG9w0BBQ4wPDAsBgkqhkiG9w0BBQwwHwQIL2oMIJbxwHoCAggAAgEgMAwGCCqGSIb3DQIJBQAwDAYIKoZIhvcNAgkFAAQgCSYXMQfMOUoEQ+pBFTrShvc6eF5nyZc2FatdBfrnpYAECC9qDCCW8cB6AgIIAA==';
const P12_PASSWORD = 'smoke';
const ED448_ROOT = 'MIIBHzCB0qADAgECAgEBMAUGAytlcDAnMSUwIwYDVQQDDBxwa2luYXRpdmUgcnVudGltZSBzbW9rZSByb290MB4XDTI2MDEwMTAwMDAwMFoXDTM2MDEwMTAwMDAwMFowJzElMCMGA1UEAwwccGtpbmF0aXZlIHJ1bnRpbWUgc21va2Ugcm9vdDAqMAUGAytlcAMhADfxjcVpLuwXun4dzZ3mdoeZSiKou2WcZwWDPd2C43/0oyMwITAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAFBgMrZXADQQDKd9RhOAHJVQbtPzLK8/320DU+j2PAwtyxNNlaWG3cFecZnximThyIJ8TIBCgAKkwd6djtNHx1S4NUcuX3vg0H';
const ED448_P7S = 'MIIC6AYJKoZIhvcNAQcCoIIC2TCCAtUCAQExDTALBglghkgBZQMEAgwwXAYJKoZIhvcNAQcBoE8ETXBraW5hdGl2ZSBydW50aW1lIHNtb2tlOiBhbiBFZDQ0OCBDTVMgc2lnbmVyIGRpZ2VzdHMgd2l0aCBTSEFLRTI1NiAoUkZDIDg0MTkpoIIBMzCCAS8wgeKgAwIBAgIBBDAFBgMrZXAwJzElMCMGA1UEAwwccGtpbmF0aXZlIHJ1bnRpbWUgc21va2Ugcm9vdDAeFw0yNjAxMDEwMDAwMDBaFw0zNjAxMDEwMDAwMDBaMC8xLTArBgNVBAMMJHBraW5hdGl2ZSBydW50aW1lIHNtb2tlIEVkNDQ4IHNpZ25lcjBDMAUGAytlcQM6AHCpi/SgqEZiOEkh2Ob3ikO+2O+JAWb0Z4ha5X87kTG7dKx0MV+TiiqA4X1Bq1Aphg7moXwxOIsRgKMSMBAwDgYDVR0PAQH/BAQDAgeAMAUGAytlcANBAN88nWl0Cu/xD7mGtTCIqHMZ4+t4eaQcFn6KvSo5aL2Idkdu7hag4vSsSJj2t9jluUUHwe/kqyyO1BmXRQJTGwkxggEqMIIBJgIBATAsMCcxJTAjBgNVBAMMHHBraW5hdGl2ZSBydW50aW1lIHNtb2tlIHJvb3QCAQQwCwYJYIZIAWUDBAIMoGswGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATBPBgkqhkiG9w0BCQQxQgRAlgoccS7HSp1NlEWpV6mywTU3vtaARn91R2eNiuDDXOEMmWqWUFIFtH1I6NRJT97EqcMNmx0oQ2oc+285PRnO8zAFBgMrZXEEckVv3IeW7ETElS/46wUD4ZG5yixxBli3vFyrMJbByKK0N7ck+F5QlW5J1sEPkOOy2JrqrsJOEu6vgGyZXbUZpfYeqFqqmDXNLnJoJtyQM8MuAS7hlsZRKw9v4+VywUJyC2GS6IEK0WPZ6VCZ5f6F/Tg8AA==';

/**
 * What each runtime answers for the Ed448 CMS signer (ADR 0022): the digest
 * is pkinative's SHAKE256 everywhere, the signature is the host's Ed448 —
 * which Node has, Bun and Chromium do not, and Deno may or may not. A host
 * that changes its answer fails this check, so the expectation is named here
 * rather than discovered.
 *
 * @returns {'verified' | 'unsupported' | 'either'}
 */
function ed448Expectation() {
    if (typeof Deno !== 'undefined') return 'either';
    if (typeof Bun !== 'undefined') return 'unsupported';
    if (typeof navigator !== 'undefined' && /Chrom(?:e|ium)\//.test(navigator.userAgent)) return 'unsupported';
    return 'verified';
}

/** @param {string} b64 */
function bytes(b64) {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
}

/** @param {unknown} ok @param {string} what */
function check(ok, what) {
    if (ok !== true) throw new Error(`runtime smoke: ${what}`);
}

/**
 * Run every check against the module namespace of dist/index.js.
 *
 * @param {Record<string, any>} m the pkinative module namespace
 * @returns {Promise<string[]>} one line per passed check; throws on the first failure
 */
export async function runChecks(m) {
    const passed = [];
    const quiet = { onDiagnostic: () => undefined };

    const x1 = m.parseCertificate(bytes(X1), quiet);
    check(m.formatDistinguishedName(x1.subject) === 'CN=ISRG Root X1,O=Internet Security Research Group,C=US', 'X1 subject');
    check(await m.verifySelfSignature(x1), 'X1 RSASSA-PKCS1-v1_5 self-signature');
    passed.push('parse + verify RSASSA-PKCS1-v1_5 (ISRG Root X1)');

    const x2 = m.parseCertificate(bytes(X2), quiet);
    check(await m.verifySelfSignature(x2), 'X2 ECDSA P-384 self-signature');
    passed.push('parse + verify ECDSA P-384, DER to P1363 (ISRG Root X2)');

    const fingerprint = await m.computeFingerprintAsync(x1.der, 'SHA-256');
    const hex = Array.from(fingerprint, (b) => b.toString(16).padStart(2, '0')).join('');
    check(hex === '96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6', 'X1 SHA-256 fingerprint');
    passed.push('SHA-256 fingerprint through Web Crypto');

    const opened = await m.openPkcs12(bytes(P12), { password: P12_PASSWORD });
    check(opened.valid && opened.integrity === 'verified', `PKCS#12 open (${opened.reasons.map((r) => r.code).join(', ')})`);
    const key = opened.keys[0];
    check(key !== undefined && key.signingKey !== undefined && key.certificate !== undefined, 'PKCS#12 key and certificate');
    const issued = await m.createCertificate({
        serialNumber: 2n,
        issuerDer: key.certificate.subject.der,
        subject: [[{ type: '2.5.4.3', value: 'pkinative runtime smoke leaf' }]],
        notBefore: Date.UTC(2026, 0, 1),
        notAfter: Date.UTC(2027, 0, 1),
        subjectPublicKey: key.certificate.subjectPublicKeyInfo.der,
    }, key.signingKey);
    check(await m.verifyCertificateSignature(m.parseCertificate(issued, quiet), key.certificate), 'certificate signed by the PKCS#12 key');
    passed.push('PKCS#12 open (PBMAC1, PBES2/AES-256-CBC) + ECDSA P-256 sign + verify');

    const pair = await crypto.subtle.generateKey({ name: 'Ed25519' }, false, ['sign', 'verify']);
    const spki = new Uint8Array(await crypto.subtle.exportKey('spki', pair.publicKey));
    const name = [[{ type: '2.5.4.3', value: 'pkinative runtime smoke Ed25519' }]];
    const self = await m.createCertificate({
        serialNumber: 3n, issuer: name, subject: name,
        notBefore: Date.UTC(2026, 0, 1), notAfter: Date.UTC(2027, 0, 1),
        subjectPublicKey: spki,
    }, { key: pair.privateKey, algorithm: { name: 'Ed25519' } });
    check(await m.verifySelfSignature(m.parseCertificate(self, quiet)), 'Ed25519 self-signature');
    passed.push('Ed25519 build + sign + verify');

    const ed448 = await m.verifySignedData({ signedData: bytes(ED448_P7S), trustAnchors: [m.parseCertificate(bytes(ED448_ROOT), quiet)], at: Date.UTC(2026, 5, 1) });
    const notChecked = ed448.reasons.length === 1 && ed448.reasons[0].code === 'PKI_REASON_SIGNATURE_NOT_CHECKED' && ed448.reasons[0].errorCode === 'PKI_CRYPTO_KEY_UNSUPPORTED';
    const outcome = ed448.valid ? 'verified' : notChecked ? 'unsupported' : `other: ${ed448.reasons.map((r) => `${r.code}${r.errorCode === undefined ? '' : `/${r.errorCode}`}`).join(', ')}`;
    const expected = ed448Expectation();
    check(expected === 'either' ? !outcome.startsWith('other') : outcome === expected, `Ed448 CMS signer: expected ${expected}, got ${outcome}`);
    passed.push(`Ed448 CMS signer (SHAKE256 digest, RFC 8419): ${outcome === 'verified' ? 'verified — this host has Ed448' : 'SIGNATURE_NOT_CHECKED / PKI_CRYPTO_KEY_UNSUPPORTED — this host has no Ed448'}${expected === 'either' ? ' (either accepted here)' : ''}`);

    return passed;
}
