#!/usr/bin/env tsx
/**
 * pkinative — frozen public-surface snapshot generator
 * ====================================================
 * `docs/assets/api.frozen.json` records every export of `src/index.ts` with
 * its kind and a canonical signature (scripts/lib/api-surface.ts says what
 * is in it and why), and every reason code, as of the version the surface
 * froze at. The `api-surface-frozen` rule of `npm run verify:docs` holds the
 * sources to it, with semantics chosen by the snapshot's `phase`:
 *
 *   - `rehearsal` (0.8.x and 0.9.x): nothing may change — no addition, no
 *     removal, no signature change, no new error or reason code. ROADMAP's
 *     "zero new exports, zero new codes", made executable.
 *   - `stable` (from 1.0.0): a removal or an incompatible change is
 *     semver-major and fails; an addition, a new optional parameter, a new
 *     optional member or a widened union is semver-minor and passes.
 *
 * Three ways to write the file, and no other:
 *
 *   (no flag)        While `asOf` is unreleased (package.json below it), the
 *                    band that takes the snapshot may retake it. Once
 *                    package.json reaches `asOf`, a change is refused.
 *   --ratchet        Stable phase only: records the surface this release
 *                    ships, so an addition made in 1.x becomes a promise too
 *                    — without it, an export added in 1.1 could be removed
 *                    in 1.2 and pass. Refused unless every change against
 *                    the snapshot is compatible. release-prepare.ts runs it
 *                    on every stable-phase bump.
 *   --rebaseline docs/adr/NNNN-….md
 *                    Rehearsal phase only: the one sanctioned way to move a
 *                    released rehearsal snapshot. The band that rehearses the
 *                    freeze is also where "every rename you will ever want" is
 *                    proposed (ROADMAP 0.9), so a rename set must be able to
 *                    land — but never silently: it names an accepted ADR that
 *                    records the change, and the move is appended to the
 *                    snapshot's `rebaselines` log, which api-surface-frozen
 *                    holds to docs/adr/. A hand edit, which is what the rule
 *                    used to suggest, leaves no trace a rule can check.
 *   --major X.0.0    Rebases the snapshot at a major release: phase `stable`,
 *                    `frozenAt` and `asOf` X.0.0. At 1.0.0 (rehearsal →
 *                    stable) it is refused unless the rehearsal held — the
 *                    surface is still exactly the rehearsed one, because
 *                    1.0.0 is the freeze itself, not a release that changes
 *                    anything. release-prepare.ts runs it when the version it
 *                    bumps to is a new major.
 *
 * Usage:
 *   npx tsx scripts/build-api-frozen.ts                  # (re)write while asOf is unreleased
 *   npx tsx scripts/build-api-frozen.ts --ratchet        # stable phase: record compatible additions
 *   npx tsx scripts/build-api-frozen.ts --rebaseline docs/adr/0013-….md   # a reviewed rename set, before 1.0
 *   npx tsx scripts/build-api-frozen.ts --major 1.0.0    # the 1.0 (or any major) release commit
 *
 * Exit: 0 written or already in sync, 1 refused, 2 bad usage or an
 * unreadable manifest.
 *
 * @module scripts/build-api-frozen
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { API_FROZEN, currentSurface, diffSurface, reasonCodes, type FrozenExport, type Reader, ADR_PATH, adrAccepted } from './lib/api-surface.js';
import { compareSemver } from './verify-docs/rules/registries.js';

/** The version the surface freezes at, when no snapshot exists yet. */
export const DEFAULT_FROZEN_AT = '0.8.0';

export type FreezePhase = 'rehearsal' | 'stable';

export interface ApiFrozen {
    readonly frozenAt: string;
    readonly phase: FreezePhase;
    readonly asOf: string;
    /** Every sanctioned move of a rehearsal snapshot: the ADR that records it, and the version it was made at. */
    readonly rebaselines?: readonly Rebaseline[] | undefined;
    readonly reasons: readonly string[];
    readonly exports: readonly FrozenExport[];
}

/** One sanctioned move of a rehearsal snapshot. */
export interface Rebaseline {
    readonly adr: string;
    readonly asOf: string;
}

export type FrozenMode =
    | { readonly kind: 'default' }
    | { readonly kind: 'ratchet' }
    | { readonly kind: 'rebaseline'; readonly adr: string }
    | { readonly kind: 'major'; readonly version: string };

export interface FrozenPlan {
    readonly action: 'write' | 'unchanged' | 'refuse';
    readonly text: string | null;
    readonly message: string;
}

const COMMENT =
    'The public surface of pkinative under semantic versioning, generated by scripts/build-api-frozen.ts: every export of src/index.ts with its kind and a canonical signature ' +
    '(read from the syntax tree of its module; comments, parameter names and member order removed — scripts/lib/api-surface.ts), and every reason code. ' +
    'The api-surface-frozen rule of scripts/verify-docs.ts holds the sources to it. phase "rehearsal" (0.8.x-0.9.x): any addition, removal or signature change fails, and so does any error or reason code the snapshots do not list. ' +
    'phase "stable" (from 1.0.0): a removal or an incompatible change is semver-major and fails; an addition is semver-minor. Error codes are frozen by docs/data/errors.frozen.json; diagnostic codes are additions-only (docs/data/diagnostics.json) and held by no snapshot.';

const major = (v: string): number => Number(v.split('.')[0]);

/** The snapshot text, one export per line so that a diff reads as the API change it is. */
export function renderApiFrozen(snapshot: ApiFrozen): string {
    const rows = snapshot.exports.map((r) => `    { "name": ${JSON.stringify(r.name)}, "kind": ${JSON.stringify(r.kind)}, "signature": ${JSON.stringify(r.signature)} }`);
    const reasons = snapshot.reasons.map((c) => `    ${JSON.stringify(c)}`);
    const moves = snapshot.rebaselines ?? [];
    const log = moves.length === 0 ? '' : `  "rebaselines": [\n${moves.map((m) => `    { "adr": ${JSON.stringify(m.adr)}, "asOf": ${JSON.stringify(m.asOf)} }`).join(',\n')}\n  ],\n`;
    return `{\n  "$comment": ${JSON.stringify(COMMENT)},\n  "frozenAt": ${JSON.stringify(snapshot.frozenAt)},\n  "phase": ${JSON.stringify(snapshot.phase)},\n  "asOf": ${JSON.stringify(snapshot.asOf)},\n`
        + log + `  "reasons": [\n${reasons.join(',\n')}\n  ],\n  "exports": [\n${rows.join(',\n')}\n  ]\n}\n`;
}

/** The snapshot of a text, or null when it is not one. */
export function parseApiFrozen(text: string): ApiFrozen | null {
    try {
        const v = JSON.parse(text) as Partial<ApiFrozen>;
        if (typeof v.frozenAt !== 'string' || typeof v.asOf !== 'string' || (v.phase !== 'rehearsal' && v.phase !== 'stable')) return null;
        if (!Array.isArray(v.exports) || !Array.isArray(v.reasons)) return null;
        if (v.rebaselines !== undefined && !(Array.isArray(v.rebaselines) && v.rebaselines.every((m) => typeof m?.adr === 'string' && typeof m.asOf === 'string'))) return null;
        return v as ApiFrozen;
    } catch {
        return null;
    }
}

/**
 * The mode release-prepare.ts runs for a bump to `version`: a new major
 * rebases, a stable-phase release ratchets, a rehearsal release writes
 * nothing (the rule, not the bump, is what refuses a change there).
 */
export function releaseModeFor(version: string, snapshot: ApiFrozen | null): FrozenMode | null {
    if (snapshot === null) return null;
    if (major(version) >= 1 && major(version) > major(snapshot.frozenAt) && /^\d+\.0\.0$/.test(version)) return { kind: 'major', version };
    return snapshot.phase === 'stable' ? { kind: 'ratchet' } : null;
}

/** What the generator would do, as a pure function of the tree (`read`), package.json's version and the mode. */
export function planApiFrozen(read: Reader, version: string, mode: FrozenMode): FrozenPlan {
    const surface = currentSurface(read);
    if (surface.problems.length > 0) {
        return { action: 'refuse', text: null, message: `the surface cannot be fingerprinted: ${surface.problems.map((p) => `${p.module}: ${p.message}`).join('; ')}` };
    }
    const reasons = reasonCodes(read).map((r) => r.code);
    const currentText = read(API_FROZEN);
    const snapshot = currentText === null ? null : parseApiFrozen(currentText);
    if (currentText !== null && snapshot === null) return { action: 'refuse', text: null, message: `${API_FROZEN} is not a snapshot (frozenAt, phase, asOf, reasons, exports) — fix it by hand` };

    const finish = (next: ApiFrozen, what: string): FrozenPlan => {
        const text = renderApiFrozen(next);
        return text === currentText
            ? { action: 'unchanged', text: null, message: `${API_FROZEN} is in sync (${next.phase}, frozenAt ${next.frozenAt}, asOf ${next.asOf}).` }
            : { action: 'write', text, message: `${what} (${next.phase}, frozenAt ${next.frozenAt}, asOf ${next.asOf}, ${String(next.exports.length)} exports, ${String(next.reasons.length)} reason codes).` };
    };

    if (mode.kind === 'major') {
        const v = mode.version;
        if (!/^\d+\.0\.0$/.test(v) || major(v) < 1) return { action: 'refuse', text: null, message: `--major takes a major release X.0.0 with X ≥ 1, not ${v}` };
        if (v !== version) return { action: 'refuse', text: null, message: `--major ${v} but package.json is at ${version} — the rebase belongs to the release commit that bumps to ${v}` };
        if (snapshot !== null && major(v) <= major(snapshot.frozenAt)) return { action: 'refuse', text: null, message: `the snapshot is already frozen at ${snapshot.frozenAt}; ${v} is not a new major` };
        if (snapshot !== null && snapshot.phase === 'rehearsal') {
            const drift = diffSurface(snapshot.exports, surface.rows);
            const reasonDrift = reasons.length !== snapshot.reasons.length || reasons.some((c) => !snapshot.reasons.includes(c));
            if (drift.length > 0 || reasonDrift) {
                return { action: 'refuse', text: null, message: `the rehearsal did not hold — ${String(drift.length)} export change(s)${reasonDrift ? ' and a reason-code change' : ''} since ${snapshot.frozenAt} (npx tsx scripts/verify-docs.ts --only api-surface-frozen lists them); 1.0.0 is the freeze itself and adds nothing over 0.9` };
            }
        }
        return finish({ frozenAt: v, phase: 'stable', asOf: v, ...(snapshot?.rebaselines === undefined ? {} : { rebaselines: snapshot.rebaselines }), reasons, exports: surface.rows }, `rebased ${API_FROZEN} at the ${v} major`);
    }

    if (mode.kind === 'rebaseline') {
        if (snapshot === null || snapshot.phase !== 'rehearsal') return { action: 'refuse', text: null, message: '--rebaseline applies to the rehearsal phase only: from 1.0.0 a change is an addition (--ratchet) or waits for the next major (--major X.0.0)' };
        if (!ADR_PATH.test(mode.adr)) return { action: 'refuse', text: null, message: `--rebaseline takes the path of an ADR, docs/adr/NNNN-slug.md, not ${mode.adr}` };
        if (!adrAccepted(read(mode.adr))) return { action: 'refuse', text: null, message: `${mode.adr} does not exist or is not "status: accepted" — a rehearsal snapshot moves only on a recorded, accepted decision` };
        const next: ApiFrozen = { ...snapshot, rebaselines: [...(snapshot.rebaselines ?? []), { adr: mode.adr, asOf: version }], reasons, exports: surface.rows };
        const drift = diffSurface(snapshot.exports, surface.rows);
        const reasonDrift = reasons.length !== snapshot.reasons.length || reasons.some((c) => !snapshot.reasons.includes(c));
        if (drift.length === 0 && !reasonDrift) return { action: 'refuse', text: null, message: 'nothing to rebaseline: the surface is the one the snapshot records' };
        return finish(next, `rebaselined ${API_FROZEN} on ${mode.adr}`);
    }

    if (mode.kind === 'ratchet') {
        if (snapshot === null || snapshot.phase !== 'stable') return { action: 'refuse', text: null, message: '--ratchet applies to the stable phase only: the rehearsal admits no change to record' };
        if (compareSemver(version, snapshot.asOf) < 0) return { action: 'refuse', text: null, message: `package.json is at ${version}, older than the snapshot's asOf ${snapshot.asOf}` };
        const breaking = diffSurface(snapshot.exports, surface.rows).filter((c) => c.verdict !== 'added' && c.verdict !== 'compatible');
        const lostReasons = snapshot.reasons.filter((c) => !reasons.includes(c));
        if (breaking.length > 0 || lostReasons.length > 0) {
            return { action: 'refuse', text: null, message: `refusing to ratchet over semver-major changes: ${[...breaking.map((c) => c.detail), ...lostReasons.map((c) => `reason code ${c} removed`)].join('; ')}` };
        }
        return finish({ ...snapshot, asOf: version, reasons, exports: surface.rows }, `ratcheted ${API_FROZEN} to the surface ${version} ships`);
    }

    const base: ApiFrozen = snapshot ?? { frozenAt: DEFAULT_FROZEN_AT, phase: 'rehearsal', asOf: DEFAULT_FROZEN_AT, reasons: [], exports: [] };
    const next: ApiFrozen = { ...base, reasons, exports: surface.rows };
    const plan = finish(next, snapshot === null ? `wrote ${API_FROZEN}` : `rewrote ${API_FROZEN} while ${base.asOf} is unreleased`);
    if (plan.action === 'write' && snapshot !== null && compareSemver(version, snapshot.asOf) >= 0) {
        return {
            action: 'refuse', text: null,
            message: `refusing — package.json is at ${version}, so the surface recorded at ${snapshot.asOf} is released (${snapshot.phase} phase). `
                + (snapshot.phase === 'rehearsal'
                    ? 'The rehearsal admits no change: revert it, or record the decision in an accepted ADR and move the snapshot with --rebaseline, which logs the move where api-surface-frozen can check it.'
                    : 'Compatible additions are recorded by --ratchet at the release that ships them; an incompatible change waits for the next major (--major X.0.0).'),
        };
    }
    return plan;
}

function parseMode(argv: readonly string[]): FrozenMode | null {
    const at = argv.indexOf('--major');
    const rb = argv.indexOf('--rebaseline');
    const known = argv.filter((a, i) => a === '--ratchet' || a === '--major' || a === '--rebaseline' || (at >= 0 && i === at + 1) || (rb >= 0 && i === rb + 1));
    if (known.length !== argv.length) return null;
    if ([argv.includes('--ratchet'), at >= 0, rb >= 0].filter(Boolean).length > 1) return null;
    if (rb >= 0) return argv[rb + 1] === undefined ? null : { kind: 'rebaseline', adr: argv[rb + 1] ?? '' };
    if (at >= 0) return argv[at + 1] === undefined ? null : { kind: 'major', version: argv[at + 1] ?? '' };
    return argv.includes('--ratchet') ? { kind: 'ratchet' } : { kind: 'default' };
}

function main(argv: readonly string[]): number {
    const mode = parseMode(argv);
    if (mode === null) {
        console.error('usage: npx tsx scripts/build-api-frozen.ts [--ratchet | --rebaseline docs/adr/NNNN-slug.md | --major X.0.0]');
        return 2;
    }
    const root = resolve(import.meta.dirname, '..');
    const read: Reader = (path) => (existsSync(join(root, path)) ? readFileSync(join(root, path), 'utf8') : null);
    let version: string;
    try {
        version = (JSON.parse(read('package.json') ?? '') as { version: string }).version;
    } catch (err) {
        console.error(`build-api-frozen: package.json — ${(err as Error).message}`);
        return 2;
    }
    const plan = planApiFrozen(read, version, mode);
    if (plan.action === 'refuse') {
        console.error(`build-api-frozen: ${plan.message}`);
        return 1;
    }
    if (plan.action === 'write' && plan.text !== null) writeFileSync(join(root, API_FROZEN), plan.text, 'utf8');
    console.log(`build-api-frozen: ${plan.message}`);
    return 0;
}

// Run only when invoked directly (keeps the module import-safe for tests and release-prepare.ts).
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
    process.exit(main(process.argv.slice(2)));
}
