/**
 * pkinative — playground bundle (`npm run docs:playground`)
 * =========================================================
 * Copies `dist/index.js` to `docs/playground/pkinative.js`, **byte for
 * byte**, so that "what the playground runs is what `npm run build`
 * produces" is literally true rather than nearly true. Nothing is minified
 * and nothing is re-bundled: a second compiler is a second set of bugs, and
 * a playground that runs different bytes from the package demonstrates a
 * library nobody can install.
 *
 * The siblings load their engine from esm.sh. pkinative cannot: it is not on
 * npm before 1.0.0, so there is nothing to load. The local copy is the
 * divergence that buys the same demonstration, and it costs a freshness
 * problem the CDN did not have — solved in two layers:
 *
 *  1. `playground-freshness` (hermetic, in `gate:fast`) compares the SHA-256
 *     of every `src/**` source and `tsup.config.ts` against
 *     `declared.playgroundBundle.sourceSha256`, the SHA-256 of the committed
 *     bundle against `bundleSha256`, its size against `maxBytes`, and checks
 *     that the loader imports `./pkinative.js` and no remote URL. It catches
 *     the defect that actually happens: editing a source and not rebuilding.
 *  2. `npm run docs:playground -- --check` (online, gate profiles `ci` and
 *     `publish`) re-derives the file from a freshly built `dist/` and
 *     compares byte for byte. It closes the gap between "the inputs hash the
 *     same" and "the output is equal".
 *
 * The copy keeps `dist/index.js`'s trailing `sourceMappingURL` comment, and
 * `index.js.map` is deliberately not copied: 429 KB of map to silence one
 * 404 that only appears with devtools open is a bad trade, and rewriting the
 * comment would end the byte-for-byte promise for a cosmetic gain.
 *
 * @module scripts/build-playground
 */

import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, posix, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const BUNDLE_SOURCE = 'dist/index.js';
export const BUNDLE_TARGET = 'docs/playground/pkinative.js';
export const SAMPLES_TARGET = 'docs/playground/samples.js';
export const MANIFEST = 'docs/assets/ecosystem.json';

/**
 * The certificates the playground offers, and the one-line description each
 * carries in the picker. They are the committed test fixtures — foreign
 * provenance recorded in tests/fixtures/PROVENANCE.md — so the playground
 * demonstrates the library on exactly the bytes the suite is held to, and
 * there is no second corpus to keep honest.
 */
export const SAMPLES: ReadonlyArray<readonly [id: string, fixture: string, label: string]> = [
    ['isrg-root-x1', 'isrg-root-x1', 'ISRG Root X1 — a self-signed RSA-4096 root'],
    ['isrg-root-x2', 'isrg-root-x2', 'ISRG Root X2 — the same root, on P-384'],
    ['lets-encrypt-r12', 'lets-encrypt-r12', "Let's Encrypt R12 — an RSA intermediate"],
    ['lets-encrypt-e7', 'lets-encrypt-e7', "Let's Encrypt E7 — an ECDSA intermediate"],
    ['letsencrypt-org-leaf', 'letsencrypt-org-leaf', 'letsencrypt.org — an end-entity with ten SANs'],
    ['rfc8410-x25519', 'rfc8410-x25519', 'RFC 8410 §10.2 — an X25519 certificate'],
];

/** `docs/playground/samples.js`, built from the committed DER fixtures. */
export function renderSamples(der: (fixture: string) => Buffer): string {
    const blocks = SAMPLES.map(([id, fixture, label]) => {
        const lines = (der(fixture).toString('base64').match(/.{1,64}/g) ?? []);
        const pem = ['-----BEGIN CERTIFICATE-----', ...lines, '-----END CERTIFICATE-----']
            .map((line) => `            '${line}',`).join('\n');
        return `    {\n        id: '${id}',\n        label: ${JSON.stringify(label).replace(/'/g, "\\u0027")},\n        pem: [\n${pem}\n        ].join('\\n') + '\\n',\n    },`;
    }).join('\n');
    return `/* ═══════════════════════════════════════════════════════════════
   pkinative.dev — playground samples
   The ${String(SAMPLES.length)} certificates the test suite uses as known-answer fixtures,
   with their provenance recorded in tests/fixtures/PROVENANCE.md. The
   playground therefore demonstrates the library on exactly the bytes the
   suite is held to.
   Generated by scripts/build-playground.ts — never hand-edited.
   ═══════════════════════════════════════════════════════════════ */

export const SAMPLES = [
${blocks}
];
`;
}

/** Every `.ts` file under `src/`, repository-relative and sorted. */
export function engineSources(root: string): string[] {
    const out: string[] = [];
    const walk = (dir: string): void => {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
            const full = join(dir, entry.name);
            if (entry.isDirectory()) walk(full);
            else if (entry.name.endsWith('.ts')) out.push(relative(root, full).split(sep).join(posix.sep));
        }
    };
    walk(join(root, 'src'));
    return out.sort();
}

/**
 * The fingerprint of everything the bundle is built from: every engine
 * source and the bundler's configuration, each hashed under its own path so
 * a rename is a change. Line endings are normalised because the same commit
 * is checked out with CRLF on Windows runners.
 */
export function sourceFingerprint(read: (path: string) => string | null, paths: readonly string[]): string {
    const hash = createHash('sha256');
    for (const path of [...paths, 'tsup.config.ts']) {
        hash.update(path);
        hash.update('\0');
        hash.update((read(path) ?? '').replace(/\r\n/g, '\n'));
        hash.update('\0');
    }
    return hash.digest('hex');
}

export function sha256(text: string): string {
    return createHash('sha256').update(text).digest('hex');
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
    const root = join(dirname(fileURLToPath(import.meta.url)), '..');
    const read = (path: string): string | null => (existsSync(join(root, path)) ? readFileSync(join(root, path), 'utf8') : null);
    const check = process.argv.includes('--check');

    const built = read(BUNDLE_SOURCE);
    if (built === null) {
        console.error(`build-playground: ${BUNDLE_SOURCE} is missing — run \`npm run build\` first`);
        process.exit(2);
    }

    const samples = renderSamples((fixture) => readFileSync(join(root, `tests/fixtures/certs/${fixture}.der`)));
    const committed = read(BUNDLE_TARGET);
    if (check) {
        const stale = [
            committed === built ? null : `${BUNDLE_TARGET} is ${committed === null ? 'missing' : 'stale'}`,
            read(SAMPLES_TARGET) === samples ? null : `${SAMPLES_TARGET} is stale`,
        ].filter((s): s is string => s !== null);
        if (stale.length === 0) {
            console.error(`build-playground: the playground runs the current build (${String(Buffer.byteLength(built))} bytes)`);
            process.exit(0);
        }
        console.error(`build-playground: ${stale.join('; ')} — run \`npm run docs:playground\` and commit the result`);
        process.exit(1);
    }

    if (committed !== built) writeFileSync(join(root, BUNDLE_TARGET), built);
    if (read(SAMPLES_TARGET) !== samples) writeFileSync(join(root, SAMPLES_TARGET), samples);

    // The three recorded values are derived, so the script writes them
    // rather than printing them to be copied: a hash transcribed by hand is
    // a hash that eventually disagrees. The rewrite is by regex, like
    // release-prepare.ts, so key order and formatting survive.
    const manifest = read(MANIFEST) ?? '';
    const values: ReadonlyArray<readonly [string, string]> = [
        ['sourceSha256', sourceFingerprint(read, engineSources(root))],
        ['bundleSha256', sha256(built)],
        ['bytes', String(Buffer.byteLength(built))],
    ];
    let updated = manifest;
    for (const [key, value] of values) {
        // Scoped to the playgroundBundle object and non-greedy, so the first
        // match after that key is the one rewritten and no sibling block with
        // a same-named field can be reached.
        // The window covers the block's $comment, which records every budget raise and grows with them.
        const pattern = new RegExp(`("playgroundBundle"[\\s\\S]{0,4000}?"${key}":\\s*)(?:"[^"]*"|\\d+)`);
        if (!pattern.test(updated)) {
            console.error(`build-playground: declared.playgroundBundle.${key} not found in ${MANIFEST}`);
            process.exit(2);
        }
        updated = updated.replace(pattern, (_m, lead: string) => `${lead}${key === 'bytes' ? value : `"${value}"`}`);
    }
    if (updated !== manifest) writeFileSync(join(root, MANIFEST), updated);

    console.error(`build-playground: ${BUNDLE_TARGET} ${committed === built ? 'unchanged' : 'written'} (${String(Buffer.byteLength(built))} bytes), ${MANIFEST} ${updated === manifest ? 'unchanged' : 'updated'}`);
}
