#!/usr/bin/env tsx
/**
 * pkinative — frozen error-code snapshot generator
 * ================================================
 * `docs/data/errors.frozen.json` records every error code, with its class,
 * as of the version the vocabulary froze at. The `error-codes-frozen` rule of
 * `npm run verify:docs` holds the registry and the code unions to it: a
 * frozen code that is removed, renamed or moved to another class fails, and
 * a code outside the snapshot must carry a `since` newer than `frozenAt`.
 *
 * This script writes the snapshot from `docs/data/errors.json` — every code
 * whose `since` is at most `frozenAt` — and exists for the one window in
 * which that is legitimate: before `frozenAt` is released, while the band
 * that freezes the vocabulary is still adding its codes. Once `package.json`
 * reaches `frozenAt` it refuses to change the file: after the freeze, no
 * command makes a removal pass, only a major version that moves `frozenAt`
 * by hand, in a reviewed commit.
 *
 * Usage:
 *   npx tsx scripts/build-errors-frozen.ts          # (re)write the snapshot while frozenAt is unreleased
 *
 * Exit: 0 written or already in sync, 1 refused (the freeze is in force and
 * the snapshot would change), 2 an unreadable registry or manifest.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ERRORS_REGISTRY, FROZEN_REGISTRY, compareSemver } from './verify-docs/rules/registries.js';

/** The version the error-code vocabulary freezes at, when no snapshot exists yet. */
const DEFAULT_FROZEN_AT = '0.8.0';

const COMMENT =
    'The error-code vocabulary as frozen under semantic versioning, generated by scripts/build-errors-frozen.ts from docs/data/errors.json. ' +
    'The error-codes-frozen rule of scripts/verify-docs.ts fails when a code listed here leaves the registry or its code union, or changes class: that is semver-major. ' +
    'A code absent from this list is an addition (semver-minor) and must carry a "since" newer than frozenAt. Diagnostic codes are not frozen; limit names freeze at 1.0.';

/** The snapshot text for `registryText`, keeping every code introduced at or before `frozenAt`, in registry order. */
export function renderFrozenSnapshot(registryText: string, frozenAt: string): string {
    const registry = JSON.parse(registryText) as { errors?: Array<{ code?: unknown; class?: unknown; since?: unknown }> };
    const rows = (registry.errors ?? [])
        .filter((e) => typeof e.code === 'string' && typeof e.class === 'string' && typeof e.since === 'string' && compareSemver(e.since, frozenAt) <= 0)
        .map((e) => `    { "code": ${JSON.stringify(e.code)}, "class": ${JSON.stringify(e.class)} }`);
    return `{\n  "$comment": ${JSON.stringify(COMMENT)},\n  "frozenAt": ${JSON.stringify(frozenAt)},\n  "codes": [\n${rows.join(',\n')}\n  ]\n}\n`;
}

function main(): number {
    const root = resolve(import.meta.dirname, '..');
    const target = join(root, FROZEN_REGISTRY);
    let registryText: string;
    let version: string;
    let frozenAt = DEFAULT_FROZEN_AT;
    let current: string | null = null;
    try {
        registryText = readFileSync(join(root, ERRORS_REGISTRY), 'utf8');
        version = (JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as { version: string }).version;
        if (existsSync(target)) {
            current = readFileSync(target, 'utf8');
            frozenAt = (JSON.parse(current) as { frozenAt: string }).frozenAt;
        }
    } catch (err) {
        console.error(`build-errors-frozen: ${(err as Error).message}`);
        return 2;
    }

    const next = renderFrozenSnapshot(registryText, frozenAt);
    if (next === current) {
        console.log(`build-errors-frozen: ${FROZEN_REGISTRY} is in sync (frozenAt ${frozenAt}).`);
        return 0;
    }
    if (compareSemver(version, frozenAt) >= 0) {
        console.error(`build-errors-frozen: refusing — package.json is at ${version}, so the ${frozenAt} freeze is in force.`);
        console.error('build-errors-frozen: removing, renaming or re-classing a frozen code is semver-major; add codes with a newer "since" instead.');
        return 1;
    }
    writeFileSync(target, next, 'utf8');
    console.log(`build-errors-frozen: wrote ${FROZEN_REGISTRY} (frozenAt ${frozenAt}, package ${version}).`);
    return 0;
}

// Run only when invoked directly (keeps the module import-safe for tests).
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
    process.exit(main());
}
