#!/usr/bin/env tsx
/**
 * pkinative — the tarball, inspected file by file (`check:package`)
 * =================================================================
 * Runs `npm pack --dry-run --json` over the built tree and compares the list
 * of files it would publish with `docs/data/package-files.json`: a file
 * added, removed, made executable, or a legal text changed, fails. Every
 * packed file is also held to the rules of scripts/lib/package-files.ts on
 * its own — nothing under src/ or tests/, no dotfile, no key or certificate,
 * every dist/ file budgeted in `declared.bundle` — so regenerating the
 * manifest cannot bless a leak. attw and publint check the package's shape,
 * smoke:install that it loads; this checks what is in it.
 *
 * Usage:
 *   npm run build && npx tsx scripts/package-files.ts            # check
 *   npm run build && npx tsx scripts/package-files.ts --update   # regenerate, then review the diff
 *
 * Exit: 0 the tarball matches its manifest; 1 it does not (or --update
 * refused a forbidden file); 2 usage, dist/ missing, or npm pack failed.
 *
 * @module scripts/package-files
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    PACKAGE_FILES_COMMAND,
    PACKAGE_FILES_MANIFEST,
    compareEntries,
    listFindings,
    manifestEntries,
    manifestShapeFindings,
    type PackageFilesManifest,
} from './lib/package-files.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const COMMENT = 'Every file `npm pack` publishes, pinned. Generated by scripts/package-files.ts from `npm pack --dry-run --json` — never hand-edited; '
    + 'checked inside the check:package gate step (added, removed, mode or legal text changed fails) and by the package-files-parity rule of verify-docs '
    + '(package.json files, declared.bundle budgets, the legal texts on disk). role is derived from the path; sha256 is pinned for the legal texts only — '
    + 'the build output is held by the byte budgets, the documents by verify-docs, and package.json changes with every version and devDependency bump.';

function npmPack(): { files: Array<{ path: string; mode: number }> } | string {
    const args = ['pack', '--dry-run', '--json', '--ignore-scripts'];
    const cli = process.env['npm_execpath'];
    const run = cli !== undefined && cli.endsWith('.js')
        ? spawnSync(process.execPath, [cli, ...args], { cwd: ROOT, encoding: 'utf8', windowsHide: true, maxBuffer: 16 * 1024 * 1024 })
        : spawnSync('npm', args, { cwd: ROOT, encoding: 'utf8', windowsHide: true, shell: process.platform === 'win32', maxBuffer: 16 * 1024 * 1024 });
    if (run.status !== 0) return `npm pack --dry-run failed\n${run.stderr}`;
    try {
        const parsed = JSON.parse(run.stdout) as Array<{ files?: Array<{ path: string; mode: number }> }>;
        const files = parsed[0]?.files;
        return Array.isArray(files) ? { files } : 'npm pack --dry-run --json reported no file list';
    } catch {
        return `npm pack --dry-run --json did not print JSON:\n${run.stdout.slice(0, 400)}`;
    }
}

function main(argv: readonly string[]): number {
    const update = argv.includes('--update');
    if (argv.some((a) => a !== '--update')) {
        console.error('Usage: npx tsx scripts/package-files.ts [--update]');
        return 2;
    }
    if (!existsSync(join(ROOT, 'dist', 'index.js'))) {
        console.error('package-files: dist/ is missing — run `npm run build` first');
        return 2;
    }
    const pack = npmPack();
    if (typeof pack === 'string') {
        console.error(`package-files: ${pack}`);
        return 2;
    }
    const actual = manifestEntries(pack.files, (p) => (existsSync(join(ROOT, p)) ? readFileSync(join(ROOT, p)) : null));
    const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { files?: string[] };
    const ecosystem = JSON.parse(readFileSync(join(ROOT, 'docs', 'assets', 'ecosystem.json'), 'utf8')) as { declared?: { bundle?: Record<string, unknown> } };
    const budgeted = Object.keys(ecosystem.declared?.bundle ?? {}).filter((k) => !k.startsWith('$'));
    const own = listFindings(actual.map((f) => f.path), pkg.files ?? [], budgeted);

    if (update) {
        if (own.length > 0) {
            for (const line of own) console.error(`✗ ${line}`);
            console.error('package-files: refusing to pin a tarball that breaks the rules above');
            return 1;
        }
        const manifest: PackageFilesManifest = { $comment: COMMENT, generatedBy: PACKAGE_FILES_COMMAND, files: actual };
        writeFileSync(join(ROOT, PACKAGE_FILES_MANIFEST), `${JSON.stringify(manifest, null, 2)}\n`);
        console.log(`package-files: wrote ${PACKAGE_FILES_MANIFEST} (${actual.length} files) — review the diff before committing it`);
        return 0;
    }

    const manifestPath = join(ROOT, PACKAGE_FILES_MANIFEST);
    if (!existsSync(manifestPath)) {
        console.error(`package-files: ${PACKAGE_FILES_MANIFEST} is missing — run ${PACKAGE_FILES_COMMAND}`);
        return 1;
    }
    const pinned = (JSON.parse(readFileSync(manifestPath, 'utf8')) as PackageFilesManifest).files;
    const findings = [...own, ...manifestShapeFindings(pinned), ...compareEntries(pinned, actual)];
    if (findings.length > 0) {
        for (const line of findings) console.error(`✗ ${line}`);
        console.error(`package-files: the tarball differs from ${PACKAGE_FILES_MANIFEST}. If the change is intended, run ${PACKAGE_FILES_COMMAND} and review the diff.`);
        return 1;
    }
    console.log(`package-files: ${actual.length} files, exactly the ${PACKAGE_FILES_MANIFEST} list`);
    return 0;
}

process.exitCode = main(process.argv.slice(2));
